#!/bin/bash
# ============================================================
#  Secure Pipeline – Dependency Installer
#  Installs all required tools locally into tools/
#  Run once before using pipeline.sh
# ============================================================

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$SCRIPT_DIR/tools"
mkdir -p "$TOOLS_DIR"

# ── Colours ─────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; BLUE='\033[0;34m'; NC='\033[0m'
ok()      { echo -e "${GREEN}  ✔  $1${NC}"; }
warn()    { echo -e "${YELLOW}  !  $1${NC}"; }
fail()    { echo -e "${RED}  ✘  $1${NC}"; exit 1; }
section() { echo -e "\n${BLUE}──────────────────────────────────────────${NC}"; \
            echo -e "${BLUE}  $1${NC}"; \
            echo -e "${BLUE}──────────────────────────────────────────${NC}"; }

download() {
    local url="$1" dest="$2" name="${3:-file}"
    echo "    → Downloading $name..."
    curl -fL --progress-bar -o "$dest" "$url" \
        || fail "Download failed. Check your internet connection.\n  URL: $url"
}

unzip_into() {
    local zipfile="$1" destdir="$2"
    mkdir -p "$destdir"
    unzip -q -o "$zipfile" -d "$destdir"
    rm -f "$zipfile"
}

banner() {
echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║     🔐 Secure Pipeline — Install Script      ║"
echo "  ║     Installing all tools into: tools/        ║"
echo "  ╚══════════════════════════════════════════════╝"
echo ""
}

banner

# ────────────────────────────────────────────────────────────
# 1. JDK 17
# ────────────────────────────────────────────────────────────
section "1/6  Java Development Kit 17"

JDK_DIR="$TOOLS_DIR/jdk17"

if [ -f "$JDK_DIR/bin/java.exe" ]; then
    ok "JDK 17 already installed at tools/jdk17"
else
    download \
        "https://api.adoptium.net/v3/binary/latest/17/ga/windows/x64/jdk/hotspot/normal/eclipse" \
        "$TOOLS_DIR/jdk17.zip" \
        "Eclipse Temurin JDK 17 (Windows x64)"

    echo "    → Extracting JDK..."
    mkdir -p "$TOOLS_DIR/_jdk_tmp"
    unzip -q -o "$TOOLS_DIR/jdk17.zip" -d "$TOOLS_DIR/_jdk_tmp"
    rm -f "$TOOLS_DIR/jdk17.zip"

    # The archive contains a single top-level folder (e.g. jdk-17.0.x+y)
    extracted_folder=$(ls "$TOOLS_DIR/_jdk_tmp" | head -1)
    cp -r "$TOOLS_DIR/_jdk_tmp/$extracted_folder/." "$JDK_DIR"
    rm -rf "$TOOLS_DIR/_jdk_tmp"

    ok "JDK 17 installed → tools/jdk17"
fi

# ────────────────────────────────────────────────────────────
# 2. Apache Maven
# ────────────────────────────────────────────────────────────
section "2/6  Apache Maven"

MVN_DIR="$TOOLS_DIR/maven"
MAVEN_VERSION="3.9.9"

if [ -f "$MVN_DIR/bin/mvn.cmd" ]; then
    ok "Maven already installed at tools/maven"
else
    download \
        "https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.zip" \
        "$TOOLS_DIR/maven.zip" \
        "Apache Maven ${MAVEN_VERSION}"

    echo "    → Extracting Maven..."
    mkdir -p "$TOOLS_DIR/_mvn_tmp"
    unzip -q -o "$TOOLS_DIR/maven.zip" -d "$TOOLS_DIR/_mvn_tmp"
    rm -f "$TOOLS_DIR/maven.zip"

    cp -r "$TOOLS_DIR/_mvn_tmp/apache-maven-${MAVEN_VERSION}/." "$MVN_DIR"
    rm -rf "$TOOLS_DIR/_mvn_tmp"

    ok "Maven ${MAVEN_VERSION} installed → tools/maven"
fi

# Write (or overwrite) the mvn bash wrapper to use fully local tools
cat > "$TOOLS_DIR/mvn" <<'MVNEOF'
#!/bin/bash
# Auto-generated by install.sh — uses local JDK 17 + local Maven
TOOLS_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export JAVA_HOME="$TOOLS_DIR/jdk17"
export PATH="$JAVA_HOME/bin:$PATH"
exec "$TOOLS_DIR/maven/bin/mvn.cmd" "$@"
MVNEOF
chmod +x "$TOOLS_DIR/mvn"
ok "tools/mvn wrapper updated to use local JDK + Maven"

# ────────────────────────────────────────────────────────────
# 3. Python virtual environment + Semgrep
# ────────────────────────────────────────────────────────────
section "3/6  Python & Semgrep"

VENV_DIR="$TOOLS_DIR/.venv"
SEMGREP_BIN="$VENV_DIR/Scripts/semgrep"

if [ -f "$SEMGREP_BIN" ] || [ -f "${SEMGREP_BIN}.exe" ]; then
    ok "Semgrep already installed in tools/.venv"
else
    # Find a usable Python 3.8+
    PYTHON=""
    for py in python3 python python3.11 python3.10 python3.9 python3.8; do
        if command -v "$py" &>/dev/null 2>&1; then
            ver_ok=$("$py" -c "import sys; print(sys.version_info >= (3,8))" 2>/dev/null || echo "False")
            if [ "$ver_ok" = "True" ]; then
                PYTHON="$py"
                break
            fi
        fi
    done

    if [ -z "$PYTHON" ]; then
        warn "Python 3.8+ not found in PATH."
        warn "Attempting automatic install via winget (Python 3.11)..."
        winget install Python.Python.3.11 \
            --accept-source-agreements --accept-package-agreements \
            || fail "Could not install Python automatically.\nPlease install Python 3.11 from https://python.org and re-run install.sh"

        # Refresh PATH after winget install
        export PATH="/c/Users/${USER}/AppData/Local/Programs/Python/Python311:/c/Users/${USER}/AppData/Local/Programs/Python/Python311/Scripts:$PATH"
        PYTHON="python"
    fi

    py_ver=$("$PYTHON" --version 2>&1)
    echo "    → Using $py_ver"
    echo "    → Creating virtual environment at tools/.venv ..."
    "$PYTHON" -m venv "$VENV_DIR"

    echo "    → Installing semgrep (this may take a minute)..."
    "$VENV_DIR/Scripts/pip" install --quiet semgrep

    ok "Semgrep installed → tools/.venv"
fi

# ────────────────────────────────────────────────────────────
# 4. Gitleaks
# ────────────────────────────────────────────────────────────
section "4/6  Gitleaks"

GITLEAKS_EXE="$TOOLS_DIR/gitleaks.exe"
GITLEAKS_VERSION="8.21.2"

if [ -f "$GITLEAKS_EXE" ]; then
    ok "Gitleaks already installed"
else
    download \
        "https://github.com/gitleaks/gitleaks/releases/download/v${GITLEAKS_VERSION}/gitleaks_${GITLEAKS_VERSION}_windows_x64.zip" \
        "$TOOLS_DIR/gitleaks.zip" \
        "Gitleaks ${GITLEAKS_VERSION}"

    echo "    → Extracting gitleaks.exe..."
    unzip -q -o "$TOOLS_DIR/gitleaks.zip" "gitleaks.exe" -d "$TOOLS_DIR/"
    rm -f "$TOOLS_DIR/gitleaks.zip"

    ok "Gitleaks installed → tools/gitleaks.exe"
fi

# ────────────────────────────────────────────────────────────
# 5. Trivy
# ────────────────────────────────────────────────────────────
section "5/6  Trivy"

TRIVY_EXE="$TOOLS_DIR/trivy.exe"
TRIVY_VERSION="0.69.0"

if [ -f "$TRIVY_EXE" ]; then
    ok "Trivy already installed"
else
    download \
        "https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_windows-64bit.zip" \
        "$TOOLS_DIR/trivy.zip" \
        "Trivy ${TRIVY_VERSION}"

    echo "    → Extracting trivy.exe..."
    unzip -q -o "$TOOLS_DIR/trivy.zip" "trivy.exe" -d "$TOOLS_DIR/"
    rm -f "$TOOLS_DIR/trivy.zip"

    ok "Trivy installed → tools/trivy.exe"
fi

# ────────────────────────────────────────────────────────────
# 6. Node.js + web dependencies
# ────────────────────────────────────────────────────────────
section "6/6  Node.js (web server)"

if command -v node &>/dev/null; then
    NODE_VER=$(node --version)
    ok "Node.js already available: $NODE_VER"
else
    warn "Node.js not found in PATH."
    warn "Attempting automatic install via winget (Node.js LTS)..."
    winget install OpenJS.NodeJS.LTS \
        --accept-source-agreements --accept-package-agreements \
        || fail "Could not install Node.js automatically.\nPlease install Node.js LTS from https://nodejs.org and re-run install.sh"

    # Refresh PATH after winget install
    export PATH="/c/Program Files/nodejs:$PATH"
    ok "Node.js LTS installed"
fi

# Install web server npm dependencies
WEB_DIR="$SCRIPT_DIR/web"
if [ -f "$WEB_DIR/package.json" ]; then
    echo "    → Installing web server npm dependencies..."
    (cd "$WEB_DIR" && npm install --quiet 2>&1)
    ok "Web server dependencies installed → web/node_modules"
fi

# ── Docker check (warn only — cannot auto-install) ───────────
if ! command -v docker &>/dev/null; then
    warn "Docker not found in PATH."
    warn "The pipeline's Maven build and Trivy stages require Docker."
    warn "Install Docker Desktop: https://www.docker.com/products/docker-desktop"
else
    DOCKER_VER=$(docker --version 2>/dev/null || echo 'unknown')
    ok "Docker available: $DOCKER_VER"
fi

# ────────────────────────────────────────────────────────────
# Done
# ────────────────────────────────────────────────────────────
echo ""
echo "  ╔══════════════════════════════════════════════╗"
echo "  ║          ✅  Installation Complete!           ║"
echo "  ╚══════════════════════════════════════════════╝"
echo ""
echo "  Installed into tools/:"
echo "    tools/jdk17/          ← Java 17 (Temurin)"
echo "    tools/maven/          ← Apache Maven ${MAVEN_VERSION}"
echo "    tools/.venv/          ← Python venv + Semgrep"
echo "    tools/gitleaks.exe    ← Gitleaks ${GITLEAKS_VERSION}"
echo "    tools/trivy.exe       ← Trivy ${TRIVY_VERSION}"
echo "    tools/mvn             ← Bash wrapper (uses local JDK+Maven)"
echo "    web/node_modules/     ← Web server (Express.js) dependencies"
echo ""
echo "  Pre-flight check:"
echo "    ✔ Java, Maven, Semgrep, Gitleaks, Trivy — all local in tools/"
echo "    ✔ Node.js — system install (used for web/server.js)"
if command -v docker &>/dev/null; then
echo "    ✔ Docker — $(docker --version 2>/dev/null)"
else
echo "    ✘ Docker — NOT FOUND (required for pipeline build + Trivy)"
fi
echo ""
echo "  Start the web UI:"
echo "    node web/server.js          (then open http://localhost:3000)"
echo ""
echo "  Or run the pipeline directly:"
echo "    bash pipeline.sh <path/to/spring-boot-project>"
echo ""
