#!/bin/bash

# ── Use local tools if JAVA_HOME / mvn not already set by pipeline.sh ────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLS_DIR="$SCRIPT_DIR/../tools"

if [ -d "$TOOLS_DIR/jdk17" ] && [ -z "$JAVA_HOME" ]; then
    export JAVA_HOME="$TOOLS_DIR/jdk17"
fi
if [ -d "$TOOLS_DIR/maven/bin" ]; then
    export PATH="$TOOLS_DIR/maven/bin:${JAVA_HOME:-$TOOLS_DIR/jdk17}/bin:$PATH"
fi

APP_DIR=${1:-.}

echo "======================================="
echo "  Scanning project for missing tests"
echo "======================================="

# Trouver tous les modules Maven (pom.xml)
MODULE_POMS=$(find "$APP_DIR" -name "pom.xml")

for POM in $MODULE_POMS; do

    MODULE_DIR=$(dirname "$POM")

    # Ignorer le parent (packaging pom)
    if grep -q "<packaging>pom</packaging>" "$POM"; then
        continue
    fi

    echo "Checking module: $MODULE_DIR"

    TEST_DIR="$MODULE_DIR/src/test/java"
    
    # Vérifier si dossier test existe
    if [ ! -d "$TEST_DIR" ]; then
        echo "  ➜ No test directory found. Creating..."
        mkdir -p "$TEST_DIR"
    fi

    # Vérifier s'il existe au moins un @Test
    TEST_COUNT=$(grep -r "@Test" "$TEST_DIR" 2>/dev/null | wc -l)

    if [ "$TEST_COUNT" -eq 0 ]; then
        echo "  ➜ No tests found. Creating default test..."

        PACKAGE_PATH="$TEST_DIR/autogenerated"
        mkdir -p "$PACKAGE_PATH"

        printf '%s\n' \
            'package autogenerated;' \
            '' \
            'import org.junit.jupiter.api.Test;' \
            'import static org.junit.jupiter.api.Assertions.assertTrue;' \
            '' \
            'class AutoGeneratedTest {' \
            '' \
            '    @Test' \
            '    void contextLoads() {' \
            '        assertTrue(true);' \
            '    }' \
            '}' \
            > "$PACKAGE_PATH/AutoGeneratedTest.java"

        echo "  ✔ Test created in $MODULE_DIR"
    else
        echo "  ✔ Tests already exist"
    fi

done

echo "======================================="
echo " Running Maven tests"
echo "======================================="

mvn -f "$APP_DIR/pom.xml" test
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "JUnit FAILED."
    exit 1
fi

echo "JUnit SUCCESS."
exit 0